disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - nesting
  - orphaned_doc_comment
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
function_parameter_count: 10
line_length: 155
cyclomatic_complexity: 20
identifier_name:
  excluded: # excluded via string array
    - id
